[package]
name = "drift-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.13.1", features = ["full"] }
drift = { path = "../programs/drift", features=["no-entrypoint"] }
anchor-client = { git = "https://github.com/drift-labs/anchor.git", rev = "ed950fe", version = "0.26.0" }
anchor-lang = { git = "https://github.com/drift-labs/anchor.git", rev = "ed950fe", version = "0.26.0" }
anchor-spl = { git = "https://github.com/drift-labs/anchor.git", rev = "ed950fe", version = "0.26.0" }
serde_json = "1.0.96"
anyhow = "1.0.71"