name: test

on:
  push:
    branches: git-update-event

jobs:
  emit-event:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["keeper-bots-v2"]
    steps:
    - name: Emit custom event
      run: |
        pwd
        ls -la
        VERSION=$(node -e "console.log(require('sdk/package.json').version);")
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/drift-labs/${{ matrix.repo }}/dispatches" \
          -d '{"event_type": "sdk-update", "client_payload": {
            "version": $VERSION
          }}'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
